### ISSUE TITLE
Load Dataset File IO

### ISSUE THREAD

**Issue by mrb24** [VizierDB/web-api-async#16]
avoid re-writing the dataset to file on mimir datastore load_dataset.  it can take significant time on large datasets.

**Comment by okennedy** [comment]
(copied from #38)

There are some situations where staging is not appropriate or necessary. @mrb24 : we should discuss

-    For what types of input is staging appropriate (e.g., we probably want to skip it for S3)
-    Where the decision should be made (i.e, Vizier or Mimir?)

In my ideal world:

-    Vizier takes care of staging for uploaded files
-    Mimir decides whether URLs require staging by their protocol and/or method (e.g., stage http, but not s3).

**Comment by okennedy** [comment]
- [ ] Change the Mimir API to include a `staging` parameter (just the API, db.loader.loadTable already has the parameter)
- [ ] Change Vizier to request staging for Uploaded Files, but not URL files.
- [ ] Change Mimir to force staging for `http` and `https` links.
- [ ] Change the UI to include a "Request Staging" option for URLs.

**Comment by okennedy** [comment]
This functionality has been resolved in Mimir
