### ISSUE TITLE
Escaping quotes and commas when saving a dataset in Python

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-api-async#52]
**Steps to reproduce**
* Create a python notebook with the following data in a python cell
```python
# Get object containing an empty dataset.
ds = vizierdb.new_dataset()

# Create a new column with a given name. The column
# position is optional.
ds.insert_column('foo')

ds.insert_row([
    "{\"action\":\"created\" , \"foo\":\"bar\"}"
])

# Create a new dataset in the data store. Expects a
# dataset object and a unique dataset name.
vizierdb.create_dataset('test1', ds)
```
Everything works correctly if you remove the ',' comma on line 9

**Comment by mrb24** [comment]
This is caused by a dataset client api create_dataset limitation. There is now a workaround:
`
vizierdb.create_dataset('test1', ds, [{'name':'delimiter', 'value':'|'}])
`

**Comment by mrb24** [comment]
blocked by https://github.com/UBOdin/mimir/issues/349

**Comment by okennedy** [comment]
As of https://github.com/VizierDB/web-api-async/pull/88 we're using JSON encoding to load updated datasets.  This problem should be fixed.
